apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-web
  labels:
    app: index
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index
        image: leehou/index-web
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: index-service
spec:
  selector:
    app.kubernetes.io/name: index-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort